CREATE DATABASE Ebloom;

CREATE TABLE IF NOT EXISTS surveys (
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	name VARCHAR(50),
	date DATE,
	type VARCHAR(100),
	company VARCHAR(100),
	questions JSON,
	created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS feedbacks (
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	question VARCHAR(225),
	score INT,
	type VARCHAR(50),
	company VARCHAR(50),
	date DATE,
	category VARCHAR(50),
	user_id INT,
	survey_id INT,
	created_at TIMESTAMP
);

CREATE TABLE companies (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(50),
	administrator VARCHAR(100),
	logo VARCHAR(300),
	updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY (id)
);
